/**
 * §0.3.0 WebUI 集成 — esbuild bundle 脚本。
 * 把 src/webui/index.ts 及其依赖打包为浏览器可加载的单个 ESM bundle。
 * 输出到 dist/webui/index.js，附带 sourcemap。
 *
 * 用法：
 *   node scripts/build-webui.mjs         # 一次性构建
 *   node scripts/build-webui.mjs --watch # watch 模式
 */
import * as esbuild from 'esbuild';
import * as path from 'node:path';
import * as url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const entryPoint = path.join(root, 'src/webui/index.ts');
const outDir = path.join(root, 'dist/webui');
const outFile = path.join(outDir, 'index.js');
const watch = process.argv.includes('--watch');

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [entryPoint],
  bundle: true,
  outfile: outFile,
  format: 'esm',
  target: 'es2022',
  platform: 'browser',
  sourcemap: 'linked',
  sourcesContent: false,
  legalComments: 'none',
  logLevel: 'info',
  // Lit 与 marked 等依赖一并打包（保持单文件部署）
  external: [],
  // Node 内置模块在浏览器侧无需 polyfill（coreReducer/index.ts 不依赖 Node API）
  banner: {
    js: '// §0.3.0 aptbot WebUI bundle — auto-generated by scripts/build-webui.mjs',
  },
};

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log('[webui] watching for changes...');
} else {
  const result = await esbuild.build(options);
  console.log(`[webui] built: ${outFile} (${result.outputFiles?.[0]?.contents?.byteLength ?? 'unknown'} bytes)`);
}
